name: ci
on:
  push:
    branches:
      - main
    paths:
      - "src/**"
      - "tests/**"
      - "Cargo.lock"
  pull_request:
    branches:
      - main
    paths:
      - "src/**"
      - "tests/**"
      - "Cargo.lock"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: read
jobs:
  rustfmt:
    runs-on: ubuntu-24.04
    if: github.actor != 'renovate[bot]'
    name: rustfmt / stable
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: Install Nix
        uses: cachix/install-nix-action@630ae543ea3a38a9a4166f03376c02c50f408342 # v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Cachix
        uses: cachix/cachix-action@5f2d7c5294214f71b873db4b969586b980625e71 # v17
        with:
          name: purpleclay
          authToken: "${{ secrets.GH_CACHIX }}"
          skipPush: true
          useDaemon: false

      - name: Cargo Format
        run: nix develop -c cargo fmt --check

  clippy:
    runs-on: ubuntu-24.04
    name: clippy / stable
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: Install Nix
        uses: cachix/install-nix-action@630ae543ea3a38a9a4166f03376c02c50f408342 # v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Cachix
        uses: cachix/cachix-action@5f2d7c5294214f71b873db4b969586b980625e71 # v17
        with:
          name: purpleclay
          authToken: "${{ secrets.GH_CACHIX }}"
          skipPush: true
          useDaemon: false

      - name: Cache Rust
        uses: Swatinem/rust-cache@e18b497796c12c097a38f9edb9d0641fb99eee32 # v2
        with:
          shared-key: "clippy"

      - name: Cargo Clippy
        run: nix develop -c cargo clippy -- -Dwarnings

  build-fast:
    runs-on: ubuntu-24.04
    if: github.event_name == 'pull_request'
    name: build-fast / linux_x86_64_musl
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: Install stable
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-unknown-linux-musl

      - name: Setup Zig
        uses: goto-bus-stop/setup-zig@abea47f85e598557f500fa1fd2ab7464fcb39406 # v2.2.1
        with:
          version: 0.13.0

      - name: Install cargo-zigbuild
        run: cargo install cargo-zigbuild

      - name: Cache
        uses: Swatinem/rust-cache@e18b497796c12c097a38f9edb9d0641fb99eee32 # v2

      - name: Build with zigbuild
        run: cargo zigbuild --locked --release --target x86_64-unknown-linux-musl

  test:
    runs-on: ${{ matrix.os }}
    name: test / ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-24.04, macos-15]
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: Install Nix
        uses: cachix/install-nix-action@630ae543ea3a38a9a4166f03376c02c50f408342 # v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Cachix
        uses: cachix/cachix-action@5f2d7c5294214f71b873db4b969586b980625e71 # v17
        with:
          name: purpleclay
          authToken: "${{ secrets.GH_CACHIX }}"
          skipPush: true
          useDaemon: false

      - name: Cache Rust
        uses: Swatinem/rust-cache@e18b497796c12c097a38f9edb9d0641fb99eee32 # v2
        with:
          shared-key: "test-${{ matrix.os }}"

      - name: Run tests
        run: nix develop -c cargo nextest run

  build:
    runs-on: ${{ matrix.platform.runs-on }}
    if: github.ref == 'refs/heads/main'
    name: build / ${{ matrix.platform.name }}
    strategy:
      matrix:
        platform:
          - name: linux_x86_64_musl
            runs-on: ubuntu-24.04
            target: x86_64-unknown-linux-musl
            use-zigbuild: true
          - name: linux_aarch64_musl
            runs-on: ubuntu-24.04
            target: aarch64-unknown-linux-musl
            use-zigbuild: true
          - name: darwin_x86_64
            runs-on: macos-15
            target: x86_64-apple-darwin
            use-zigbuild: false
          - name: darwin_aarch64
            runs-on: macos-15
            target: aarch64-apple-darwin
            use-zigbuild: false
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: Install stable
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.platform.target }}

      - name: Setup Zig
        if: ${{ matrix.platform.use-zigbuild }}
        uses: goto-bus-stop/setup-zig@abea47f85e598557f500fa1fd2ab7464fcb39406 # v2.2.1
        with:
          version: 0.13.0

      - name: Install cargo-zigbuild
        if: ${{ matrix.platform.use-zigbuild }}
        run: cargo install cargo-zigbuild

      - name: Cache
        uses: Swatinem/rust-cache@e18b497796c12c097a38f9edb9d0641fb99eee32 # v2

      - name: Build with zigbuild
        if: ${{ matrix.platform.use-zigbuild }}
        run: cargo zigbuild --locked --release --target ${{ matrix.platform.target }}

      - name: Build with cargo
        if: ${{ !matrix.platform.use-zigbuild }}
        run: cargo build --locked --release --target ${{ matrix.platform.target }}
